# Dockerfile.jupyter
FROM jupyter/base-notebook:python-3.11

WORKDIR /home/jovyan/work

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.password=''"]
