# Common training parameters for the models
split_data: 
  train_fraction: 0.8
  random_state: 42
  target_column: 'is_repeated_buyers'

# Parameters for each model type
random_forest_params:
  n_estimators: 100
  max_depth: 10
  oob_score: true
  random_state: 42
  warm_start: true

binary_logistic_params:
  max_iter: 200
  random_state: 42


gradient_boosting_params:
  n_estimators: 100
  SEED: 23
  learning_rate: 0.05
  random_state: 23
  max_features: 5



