# Common training parameters for the models
split_data: 
    train_fraction: 0.7
    test_fraction: 0.15
    val_fraction: 0.15
    random_state: 42
    target_column: 'is_repeat_buyer'

# Parameters for each model type
random_forest_params:
  model_params_rfc:
    oob_score: true
    random_state: 42
    warm_start: true
    class_weight: "balanced"
  param_grid_rfc:
    n_estimators: [100, 200, 500]
    max_depth: [10, 20, 30, None]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: ['sqrt', 'log2']


binary_logistic_params:
  model_params_blr:
    random_state: 42
    n_jobs: -1
    max_iter: 10000
    class_weight: "balanced"
  param_grid_blr:
    - solver: ['liblinear']
      penalty: ['l2', 'l1']
      C: [0.01, 0.1, 1, 10, 100]

    - solver: ['saga']
      penalty: ['elasticnet', 'l2']
      C: [0.01, 0.1, 1, 10, 100]
      l1_ratio: [0.5]

delivery_time_col: "delivered_in_days"

installment_col: "payment_installments"
value_col: "payment_value"
sequential_col: "payment_sequential"
payment_type_col: "payment_type"

category_col: "product_category_name_english" 
value_colm: "price"
threshold: 0.8


